version: '3'
networks:
  backend:
services:
  id:
    image: kingdarkness/lumen-php:8.1-apache-socket
    restart: always
    ports:
    - '8487:80'
    volumes:
      - ./:/var/www/html
    networks:
      - backend
  id_scheduler:
    image: kingdarkness/lumen-php:8.1-apache-socket
    restart: always
    ports:
    - '8488:80'
    volumes:
      - ./:/var/www/html
    networks:
      - backend
  mariadb:
    image: mariadb:10.3.9
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=trung
      - MYSQL_DATABASE=docker-test
    ports:
      - 33061:3306
    networks:
      - backend
volumes:
  mariadb: